//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsMatchingGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsMatchingGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Card1 {
            get {
                object obj = ResourceManager.GetObject("Card1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Card2 {
            get {
                object obj = ResourceManager.GetObject("Card2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Card3 {
            get {
                object obj = ResourceManager.GetObject("Card3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Card4 {
            get {
                object obj = ResourceManager.GetObject("Card4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Card5 {
            get {
                object obj = ResourceManager.GetObject("Card5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Card6 {
            get {
                object obj = ResourceManager.GetObject("Card6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Card7 {
            get {
                object obj = ResourceManager.GetObject("Card7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Card8 {
            get {
                object obj = ResourceManager.GetObject("Card8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards for matching.
        /// </summary>
        internal static string CardsForMatching {
            get {
                return ResourceManager.GetString("CardsForMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched cards turned back..
        /// </summary>
        internal static string CardsTurnedBack {
            get {
                return ResourceManager.GetString("CardsTurnedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A smiling man with a red coat and arms outstretched, standing in front of 3 large Daleks and a TARDIS. The Daleks seem to be raised above the grass beneath them, and a slightly cloudy sky is in the background..
        /// </summary>
        internal static string DefaultCard1Description {
            get {
                return ResourceManager.GetString("DefaultCard1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daleks in Blackpool.
        /// </summary>
        internal static string DefaultCard1Name {
            get {
                return ResourceManager.GetString("DefaultCard1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small brown stone lighthouse, with an upper small balcony and a lower bigger balcony. A covered sitting area is at the base of the lighthouse. In front of the lighthouse in the stone ground are anchor and compass symbols, and in the background is a grey cloudy sky..
        /// </summary>
        internal static string DefaultCard2Description {
            get {
                return ResourceManager.GetString("DefaultCard2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Lighthouse in Fleetwood.
        /// </summary>
        internal static string DefaultCard2Name {
            get {
                return ResourceManager.GetString("DefaultCard2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A first-person view looking down on two portions of fish and chips in trays and paper. In the background is a concrete path, and two partially shown shoes..
        /// </summary>
        internal static string DefaultCard3Description {
            get {
                return ResourceManager.GetString("DefaultCard3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish and Chips in Cleveleys.
        /// </summary>
        internal static string DefaultCard3Name {
            get {
                return ResourceManager.GetString("DefaultCard3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small, very old hexagonal red stone building, with castellated battlements housing a cross. Arched windows on the sides of the building are bricked-up from the inside. The building sits on grass, with a bay and cloudy sky in the background..
        /// </summary>
        internal static string DefaultCard4Description {
            get {
                return ResourceManager.GetString("DefaultCard4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cockersand Abbey.
        /// </summary>
        internal static string DefaultCard4Name {
            get {
                return ResourceManager.GetString("DefaultCard4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A white windmill with a black roof and black sails. The windmill has stairs going up to a black door, and black windows. In the background is a street of houses and a clear, blue sky..
        /// </summary>
        internal static string DefaultCard5Description {
            get {
                return ResourceManager.GetString("DefaultCard5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lytham St Annes Windmill.
        /// </summary>
        internal static string DefaultCard5Name {
            get {
                return ResourceManager.GetString("DefaultCard5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stone ruins of a large, very old abbey. The abbey has no roof or windows, and the sun shines through the arches from behind the abbey. In the foreground is a lawn housing multiple large stone graves, and in the background is a clear blue sky..
        /// </summary>
        internal static string DefaultCard6Description {
            get {
                return ResourceManager.GetString("DefaultCard6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolton Abbey.
        /// </summary>
        internal static string DefaultCard6Name {
            get {
                return ResourceManager.GetString("DefaultCard6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large stone obelisk in a town square, with buildings and trees nearby. The sun shines on the obelisk, with a slightly cloudy, blue sky in the background. At the base of the obelisk are six red wreaths..
        /// </summary>
        internal static string DefaultCard7Description {
            get {
                return ResourceManager.GetString("DefaultCard7Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harrogate Obelisk.
        /// </summary>
        internal static string DefaultCard7Name {
            get {
                return ResourceManager.GetString("DefaultCard7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small square stone building with an opening on the near side. Above the opening is a Greek inscription. Railing surrounds the top of the building, and a sundial sits at the centre of the top. In the background is rocky grassland, with rolling hills in the far background along with a slightly cloudy, blue sky..
        /// </summary>
        internal static string DefaultCard8Description {
            get {
                return ResourceManager.GetString("DefaultCard8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hampsfell Hospice.
        /// </summary>
        internal static string DefaultCard8Name {
            get {
                return ResourceManager.GetString("DefaultCard8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Picture Names and Descriptions.
        /// </summary>
        internal static string ExportDlgTitle {
            get {
                return ResourceManager.GetString("ExportDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load 8 pictures before exporting their names and descriptions..
        /// </summary>
        internal static string ExportWarning {
            get {
                return ResourceManager.GetString("ExportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face down.
        /// </summary>
        internal static string FaceDown {
            get {
                return ResourceManager.GetString("FaceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Picture Names and Descriptions.
        /// </summary>
        internal static string ImportDlgTitle {
            get {
                return ResourceManager.GetString("ImportDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchingGamePictureDetails.
        /// </summary>
        internal static string ImportExportDefaultFileName {
            get {
                return ResourceManager.GetString("ImportExportDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please load 8 pictures before importing their names and descriptions..
        /// </summary>
        internal static string ImportWarning {
            get {
                return ResourceManager.GetString("ImportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide 8 named pictures in the Your Picture Details table..
        /// </summary>
        internal static string PictureNamesWarning {
            get {
                return ResourceManager.GetString("PictureNamesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to lose the changes made to the settings?.
        /// </summary>
        internal static string SettingsChangeWarning {
            get {
                return ResourceManager.GetString("SettingsChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Game Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s a match!.
        /// </summary>
        internal static string ThatsAMatch {
            get {
                return ResourceManager.GetString("ThatsAMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned over.
        /// </summary>
        internal static string TurnedOver {
            get {
                return ResourceManager.GetString("TurnedOver", resourceCulture);
            }
        }
    }
}
